set(_CATKIN_CURRENT_PACKAGE "image")
set(image_VERSION "0.0.0")
set(image_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(image_PACKAGE_FORMAT "1")
set(image_BUILD_DEPENDS "cv_bridge" "image_transport" "message_generation" "opencv2" "sensor_msgs")
set(image_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "message_runtime" "opencv2" "sensor_msgs")
set(image_BUILDTOOL_DEPENDS "catkin")
set(image_BUILDTOOL_EXPORT_DEPENDS )
set(image_EXEC_DEPENDS "cv_bridge" "image_transport" "message_runtime" "opencv2" "sensor_msgs")
set(image_RUN_DEPENDS "cv_bridge" "image_transport" "message_runtime" "opencv2" "sensor_msgs")
set(image_TEST_DEPENDS )
set(image_DOC_DEPENDS )
set(image_URL_WEBSITE "")
set(image_URL_BUGTRACKER "")
set(image_URL_REPOSITORY "")
set(image_DEPRECATED "")